---
title: "LR Script"
author: "Donal O'Shea"
date: "7/6/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
cnvs_total_mods = read.csv("cnvs_total_mods.csv")

```
```{r}
cnvs_all = cnvs_total_mods[,c(5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29)]
model_first <- glm(cohort ~.,family=binomial,data=cnvs_all)
summary(model_first)
```


```{r}
data_select = cnvs_total_mods[,c(5,7,10,17,20,21,23,24,28)]



library(caTools)
#use caTools function to split, SplitRatio for 70%:30% splitting
data1= sample.split(data_select,SplitRatio = 0.7)

#subsetting into Train data
train =subset(data_select,data1==TRUE)

#subsetting into Test data
test =subset(data_select,data1==FALSE)

model <- glm(cohort ~.,family=binomial,data=train)

summary(model)
```

```{r}
anova(model, test="Chisq")
```


```{r}
fitted.results <- predict(model,newdata=test,type='response')
fitted.results <- ifelse(fitted.results > 0.9,"control","cases")

table(fitted.results,test$cohort)

misClasificError <- mean(fitted.results != test$cohort)
print(paste('Accuracy',1-misClasificError))
```

```{r}
library(ROCR)
p <- predict(model, newdata=test, type="response")
pr <- prediction(p, test$cohort)
prf_1 <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf_1)
abline(a=0, b= 1)

auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
auc
```

```{r}
asd_dataset = read.csv("ASD_dataset.csv")

```


```{r}
data_test = asd_dataset[,c(4:12)]
levels(data_test$cohort)

```

```{r}

fitted.results <- predict(model,newdata=data_test,type='response')
fitted.results <- ifelse(fitted.results > 0.95,"control","cases")

table(fitted.results,data_test$cohort)

misClasificError <- mean(fitted.results != data_test$cohort)
print(paste('Accuracy',1-misClasificError))

```



```{r}
library(ROCR)
p <- predict(model, newdata=data_test, type="response")
pr <- prediction(p, data_test$cohort)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)

auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
auc
```






```{r}

```


